[package]
name = "simple_text_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.serde_json]
version = "1.0"
optional = true

[features]
default = []
json = ["serde_json"]